### PR TITLE
Update pay-fees.html

### PR DESCRIPTION
**Pull request by JadaPeters**
The fees have increased as of June 2024

### CODE REVIEW

**Review by itbsc — COMMENTED** [review]
Were the stripe products also updated? Looks like they still have old prices...

**Comment by JadaPeters** [comment]
> Were the strip products also updated? Looks like they still have old prices...

Correct, I haven't updated the strip products yet, but I plan to make those changes along with other minor updates to the site this week.

**Comment by itbsc** [comment]
> > Were the strip products also updated? Looks like they still have old prices...
> 
> Correct, I haven't updated the strip products yet, but I plan to make those changes along with other minor updates to the site this week.

Please reach out to the finance people to make sure they update those stripe products.

**Review by itbsc — APPROVED** [review]
LGTM

**Pull request merged**
